name: Chef Mata Smoke Test

on:
  schedule:
    - cron: '5 0 */3 * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: windows-latest
    env:
      CHEF_MATA_USER: ${{ secrets.CHEF_MATA_USER }}
      CHEF_MATA_PASSWORD: ${{ secrets.CHEF_MATA_PASSWORD }}
      CHEF_MATA_ADMIN_LOGIN: ${{ secrets.CHEF_MATA_ADMIN_LOGIN }}
      CHEF_MATA_ADMIN_URL: ${{ secrets.CHEF_MATA_ADMIN_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/Chef_Mata/smoke_test.cy.js
